AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  telegramWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: telegramWebhook
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: s3://ygotcg-telegram-bot-bucket/9ce01260ad034221c397e3581de7bf51
      Description: Telegram bot webhook
      Timeout: 10
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSLambdaDynamoDBExecutionRole
      - AmazonDynamoDBReadOnlyAccess
      Tracing: Active
  updateDatabaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateDatabase
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: s3://ygotcg-telegram-bot-bucket/de442bf0bae5dfe5581c130e28abeea7
      Description: YGO TCG card database update
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - DatabaseAdministrator
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue:
              Fn::GetAtt:
              - updateDatabaseSQS
              - Arn
            ScalingConfig:
              MaximumConcurrency: 10
      Tracing: Active
  updateDatabaseSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: updateDatabaseSQS
  updateDatabaseSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - SQS:SendMessage
          - SQS:ReceiveMessage
          Effect: Allow
          Principal:
            AWS:
            - arn:aws:iam::103245333395:user/gfceccon
          Resource:
            Fn::GetAtt:
            - updateDatabaseSQS
            - Arn
      Queues:
      - Ref: updateDatabaseSQS
